#!/usr/bin/env python3
"""Generate question banks 8, 9, 10 and the aggregator."""
import random
import os

random.seed(42)
APP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "app")

FUNCS = ["process_data", "handle_request", "fetch_item", "compute_result", "run_task",
         "transform_input", "validate_payload", "execute_query", "dispatch_event",
         "aggregate_results", "parse_response", "build_config", "serialize_output",
         "decode_message", "filter_records"]
VARS = ["result", "output", "data", "response", "payload",
        "value", "item", "record", "buffer", "stream"]
NUMS = list(range(2, 22))


def gen_concurrency_networking(count=500):
    """Generate concurrency and networking questions."""
    base = []
    # asyncio questions
    for i, (concept, code_desc, wrong1, wrong2, wrong3) in enumerate([
        ("asyncio.gather()", "runs multiple coroutines concurrently and collects results",
         "runs coroutines sequentially in order", "creates new threads for each coroutine",
         "blocks the event loop until all complete synchronously"),
        ("asyncio.create_task()", "schedules a coroutine to run on the event loop as a Task",
         "creates a new OS thread for the coroutine", "blocks until the coroutine completes",
         "converts a synchronous function to async"),
        ("asyncio.Semaphore(n)", "limits concurrent access to n coroutines at a time",
         "creates n new threads", "limits total memory usage to n bytes",
         "sets the maximum event loop iterations"),
        ("asyncio.Queue", "provides async-safe FIFO queue for producer-consumer patterns",
         "is a thread-safe queue for multiprocessing", "stores data persistently on disk",
         "is only usable in synchronous code"),
        ("asyncio.wait_for(coro, timeout)", "cancels the coroutine if it exceeds the timeout",
         "returns None if timeout is exceeded", "raises TimeoutError but lets coroutine continue",
         "pauses the event loop for timeout seconds"),
        ("asyncio.shield()", "protects a coroutine from being cancelled by its parent",
         "encrypts the coroutine return value", "prevents memory leaks in the coroutine",
         "makes the coroutine run in a separate process"),
        ("asyncio.run_in_executor()", "runs blocking code in a thread pool without blocking the event loop",
         "creates a new event loop in a thread", "converts async code to synchronous",
         "executes code in a subprocess"),
        ("event loop.call_soon()", "schedules a callback for the next iteration of the event loop",
         "executes the callback immediately", "creates a new thread for the callback",
         "delays execution by 1 second"),
        ("asyncio.Event", "allows coroutines to wait until a flag is set by another coroutine",
         "is a threading.Event wrapper for async code", "triggers an OS-level signal",
         "logs events to a file"),
        ("asyncio.Lock", "provides mutual exclusion between coroutines (not threads)",
         "is identical to threading.Lock", "locks file descriptors",
         "prevents garbage collection"),
    ]):
        base.append({
            "question_text": f"What does {concept} do in asyncio?\n\nCode context:\n  async def {{FN}}():\n      # uses {concept}\n      ...",
            "correct": f"It {code_desc}",
            "w1": f"It {wrong1}", "w2": f"It {wrong2}", "w3": f"It {wrong3}",
        })

    # Threading questions
    for concept, correct, w1, w2, w3 in [
        ("threading.Lock()", "provides mutual exclusion - only one thread holds it at a time",
         "allows multiple threads to hold it simultaneously", "is reentrant by default",
         "only works with asyncio coroutines"),
        ("threading.RLock()", "allows the same thread to acquire it multiple times without deadlock",
         "is faster than Lock but less safe", "automatically releases when thread ends",
         "can only be acquired once per thread"),
        ("threading.Condition()", "allows threads to wait for a condition and be notified by others",
         "checks CPU conditions like temperature", "is a replacement for if statements",
         "only works with daemon threads"),
        ("ThreadPoolExecutor.submit()", "returns a Future object representing the pending result",
         "blocks until the callable completes", "creates a new process for each call",
         "is the same as calling the function directly"),
        ("ThreadPoolExecutor.map()", "applies function to iterable elements in parallel, returning results in order",
         "returns results in completion order", "creates one thread per CPU core regardless of input",
         "is identical to builtin map()"),
        ("threading.Barrier(n)", "blocks until n threads have called wait(), then releases all",
         "limits total threads to n", "creates n threads automatically",
         "is a replacement for join()"),
        ("threading.Semaphore(n)", "allows up to n threads to access a resource concurrently",
         "creates n copies of the resource", "is the same as creating n locks",
         "limits CPU usage to n percent"),
        ("daemon threads", "are terminated abruptly when the main thread exits",
         "continue running after main thread exits", "have higher priority than normal threads",
         "cannot access shared memory"),
        ("thread.join(timeout)", "blocks the calling thread until target completes or timeout expires",
         "kills the thread after timeout", "creates a new thread that monitors the target",
         "merges two threads into one"),
        ("threading.local()", "provides thread-local storage where each thread sees its own data",
         "creates a lock local to the current scope", "is shared memory accessible by all threads",
         "stores data in the thread stack frame"),
    ]:
        base.append({
            "question_text": f"In Python threading, what is the behavior of {concept}?\n\n  import threading\n  # using {concept} in {{FN}}",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Multiprocessing questions
    for concept, correct, w1, w2, w3 in [
        ("multiprocessing.Pool.map()", "distributes work across processes, bypassing the GIL for CPU parallelism",
         "uses threads internally despite the module name", "shares the GIL across processes",
         "is limited to I/O-bound tasks only"),
        ("multiprocessing.Queue", "provides process-safe FIFO queue using pipes and locks internally",
         "uses shared memory without any synchronization", "is the same as queue.Queue",
         "only works on Linux systems"),
        ("multiprocessing.Value/Array", "provides shared memory objects accessible by multiple processes with locking",
         "copies data between processes on each access", "is only for read-only data sharing",
         "requires explicit serialization with pickle"),
        ("Process.start() vs .run()", "start() creates a new process; run() executes in the current process",
         "they are identical in behavior", "run() creates the process while start() just initializes",
         "start() is deprecated in favor of run()"),
        ("multiprocessing.shared_memory", "creates named shared memory blocks accessible across processes without pickling",
         "is slower than Queue for all data sizes", "requires the data to be JSON serializable",
         "only supports integer arrays"),
    ]:
        base.append({
            "question_text": f"What is true about {concept}?\n\n  from multiprocessing import ...\n  def {{FN}}(): ...",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Networking questions
    for concept, correct, w1, w2, w3 in [
        ("socket.socket(AF_INET, SOCK_STREAM)", "creates a TCP socket for reliable, ordered byte stream communication",
         "creates a UDP socket for fast but unreliable delivery", "creates a Unix domain socket",
         "creates a raw socket for packet manipulation"),
        ("httpx.AsyncClient", "provides connection pooling and HTTP/2 support for async HTTP requests",
         "is a synchronous-only HTTP client", "requires manually managing TCP connections",
         "cannot handle cookies or redirects"),
        ("aiohttp.ClientSession", "maintains a connection pool and cookie jar across multiple async requests",
         "creates a new TCP connection for every request", "is a synchronous HTTP wrapper",
         "cannot be used as a context manager"),
        ("asyncio.open_connection()", "returns (reader, writer) stream pair for TCP communication",
         "opens a file on the filesystem", "creates a UDP socket",
         "establishes a WebSocket connection"),
        ("WebSocket vs HTTP", "maintains a persistent bidirectional connection for real-time communication",
         "requires a new connection for each message like HTTP", "is always less efficient than HTTP polling",
         "cannot send data from server to client"),
        ("connection pooling in HTTP clients", "reuses TCP connections to avoid repeated TLS handshakes and reduce latency",
         "creates more connections to increase throughput", "caches HTTP responses on disk",
         "pools DNS lookups to speed up resolution"),
        ("socket.setblocking(False)", "makes operations return immediately or raise BlockingIOError if not ready",
         "disables the Nagle algorithm", "enables keep-alive packets",
         "sets infinite timeout on the socket"),
        ("select/poll/epoll", "monitors multiple file descriptors for I/O readiness without blocking",
         "selects the best network interface for sending", "polls the DNS server for updates",
         "is only needed for UDP sockets"),
        ("SO_REUSEADDR socket option", "allows binding to a port still in TIME_WAIT state from a previous connection",
         "allows multiple processes to bind to the same port simultaneously", "reuses the same TCP sequence numbers",
         "disables port randomization for security"),
        ("asyncio.start_server()", "creates a TCP server that calls a callback for each new connection",
         "starts a multiprocessing server", "creates a UDP listener",
         "is a synchronous server factory"),
    ]:
        base.append({
            "question_text": f"What is the purpose of {concept} in Python networking?\n\n  # {{FN}} uses {concept.split()[0]}...",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Additional conceptual questions
    for q, c, w1, w2, w3 in [
        ("What happens when you await asyncio.gather(*tasks, return_exceptions=True)?",
         "Exceptions from tasks are returned as values in the results list",
         "All other tasks are cancelled when one raises", "The gather itself raises the first exception",
         "Exceptions are logged and suppressed silently"),
        ("Why does the GIL limit CPU-bound threading performance?",
         "Only one thread executes Python bytecode at a time even on multi-core systems",
         "The GIL prevents threads from being created", "The GIL only affects I/O operations",
         "The GIL has been removed in Python 3.10+"),
        ("When should you prefer asyncio over threading?",
         "For I/O-bound workloads with many concurrent connections (thousands of sockets)",
         "For CPU-intensive calculations like matrix multiplication",
         "When you need true parallelism on multiple cores",
         "When working with C extensions that release the GIL"),
        ("What is the difference between asyncio.wait() FIRST_COMPLETED vs ALL_COMPLETED?",
         "FIRST_COMPLETED returns as soon as any task finishes; ALL_COMPLETED waits for all",
         "FIRST_COMPLETED cancels remaining tasks; ALL_COMPLETED does not",
         "There is no behavioral difference between them",
         "FIRST_COMPLETED is faster because it uses threads"),
        ("What does concurrent.futures.as_completed() yield?",
         "Futures in the order they complete, not submission order",
         "Futures in submission order", "Only successfully completed futures",
         "Raw return values, not Future objects"),
        ("How do you safely share data between asyncio tasks?",
         "Use asyncio.Queue or simple variables since tasks share the same thread",
         "Use threading.Lock since tasks run on different threads",
         "Use multiprocessing.Value for shared memory",
         "You cannot share data between tasks"),
        ("What is the purpose of asyncio.ensure_future()?",
         "Wraps a coroutine or awaitable into a Task/Future; accepts both coroutines and Futures",
         "Guarantees that a coroutine will eventually run",
         "Prevents a future from being garbage collected",
         "Is identical to asyncio.create_task() in every way"),
        ("What happens if you call asyncio.run() inside an already-running loop?",
         "Raises RuntimeError because nested event loops are not allowed",
         "Creates a nested event loop automatically",
         "Reuses the existing event loop",
         "Silently does nothing and returns None"),
        ("How does trio differ from asyncio in error handling?",
         "Trio uses structured concurrency with cancel scopes and exception groups",
         "Trio ignores all exceptions in child tasks",
         "Trio and asyncio handle errors identically",
         "Trio does not support exception handling"),
        ("What is the overhead of creating a new thread vs using a thread pool?",
         "New thread creation involves OS-level allocation; pools amortize this cost over many tasks",
         "Thread pools are always slower due to queue overhead",
         "There is no measurable difference",
         "Thread pools use more memory per task"),
        ("What does socket.settimeout(0) do?",
         "Makes the socket non-blocking, equivalent to setblocking(False)",
         "Sets an infinite timeout", "Disables the socket timeout completely",
         "Makes recv() return empty bytes immediately"),
        ("How does HTTP/2 multiplexing improve performance?",
         "Multiple requests share a single TCP connection using streams, avoiding head-of-line blocking at HTTP level",
         "It creates multiple TCP connections automatically",
         "It compresses all request bodies",
         "It uses UDP instead of TCP for speed"),
        ("What is the purpose of asyncio.TaskGroup in Python 3.11+?",
         "Provides structured concurrency where all tasks are awaited and errors propagate correctly",
         "Groups tasks for priority scheduling",
         "Limits the number of concurrent tasks",
         "Is a replacement for ThreadPoolExecutor"),
        ("What problem does connection keep-alive solve?",
         "Avoids TCP handshake overhead for sequential requests to the same server",
         "Keeps the server process alive between requests",
         "Maintains client-side state between requests",
         "Prevents connection timeouts from firewalls"),
        ("What is backpressure in async networking?",
         "A mechanism to slow down producers when consumers cannot keep up with incoming data",
         "The pressure on the network cable from too many packets",
         "A type of network congestion at the router level",
         "The CPU load from too many open connections"),
    ]:
        base.append({"question_text": q, "correct": c, "w1": w1, "w2": w2, "w3": w3})

    # Expand to 500
    questions = []
    for i in range(count):
        b = base[i % len(base)].copy()
        fn = FUNCS[i % len(FUNCS)]
        questions.append({
            "question_text": b["question_text"].replace("{FN}", fn),
            "option_a": b["correct"].replace("{FN}", fn),
            "option_b": b["w1"].replace("{FN}", fn),
            "option_c": b["w2"].replace("{FN}", fn),
            "option_d": b["w3"].replace("{FN}", fn),
            "correct_answer": "A",
            "difficulty": "advanced",
            "topic": "concurrency_networking",
        })
    return questions

print('gen_concurrency_networking defined')


def gen_security_auth(count=500):
    """Generate security and authentication questions."""
    base = []
    for concept, correct, w1, w2, w3 in [
        ("JWT token structure", "consists of header.payload.signature, each base64url-encoded",
         "is a single encrypted binary blob", "contains only the user password hash",
         "must be stored in a database to be valid"),
        ("JWT token expiration (exp claim)", "is checked during validation; expired tokens should be rejected",
         "is optional and never checked", "automatically refreshes the token",
         "extends each time the token is used"),
        ("refresh tokens", "are long-lived tokens used to obtain new access tokens without re-authentication",
         "are shorter-lived than access tokens", "replace passwords entirely",
         "are sent with every API request"),
        ("bcrypt password hashing", "incorporates a salt and work factor, making brute force attacks computationally expensive",
         "is a fast reversible encryption algorithm", "stores passwords in plaintext with a prefix",
         "is deprecated in favor of MD5"),
        ("argon2 for password hashing", "is memory-hard, making GPU/ASIC attacks expensive by requiring significant RAM",
         "is faster than MD5 for better performance", "uses only CPU cycles, no memory",
         "is the same algorithm as bcrypt with different parameters"),
        ("OAuth2 authorization code flow", "redirects user to auth server, returns code, then exchanges code for token server-side",
         "sends username/password directly to the resource server",
         "uses only client-side JavaScript with no server component",
         "sends the access token in the URL fragment only"),
        ("OAuth2 client credentials flow", "is for server-to-server auth where no user is involved, using client_id and secret",
         "requires user login via a browser redirect",
         "is the same as the authorization code flow",
         "uses only API keys without any OAuth standards"),
        ("HMAC signature verification", "recomputes the HMAC with the shared secret and compares using constant-time comparison",
         "decrypts the signature to reveal the original message",
         "checks if the signature length matches the expected size",
         "verifies the signature against a public certificate authority"),
        ("secrets.token_urlsafe(n)", "generates a cryptographically secure random URL-safe string of n random bytes",
         "generates a predictable token based on the current timestamp",
         "creates a token that expires after n seconds",
         "encodes an existing string in URL-safe format"),
        ("SQL injection prevention", "uses parameterized queries (placeholders) so user input is never part of the SQL syntax",
         "escapes quotes in user input using string replace",
         "validates that input contains only letters",
         "limits input length to 50 characters"),
        ("XSS prevention in web apps", "escapes HTML entities in user-supplied content before rendering in the browser",
         "blocks all JavaScript on the page",
         "only allows GET requests from forms",
         "requires HTTPS for all pages"),
        ("CORS (Cross-Origin Resource Sharing)", "uses HTTP headers to control which origins can access resources via browser requests",
         "encrypts cross-origin requests automatically",
         "blocks all requests from different domains permanently",
         "is enforced by the server operating system"),
        ("rate limiting implementation", "tracks request counts per client (IP/token) within time windows, rejecting excess requests",
         "slows down the server response time for all users",
         "limits the total number of users who can register",
         "only applies to POST requests"),
        ("RBAC (Role-Based Access Control)", "assigns permissions to roles, then assigns roles to users, checking role permissions on each request",
         "gives all authenticated users the same permissions",
         "uses only the username to determine access",
         "requires a separate database for each role"),
        ("Fernet symmetric encryption", "provides authenticated encryption (AES-CBC + HMAC) with a URL-safe token format",
         "is an asymmetric RSA encryption scheme",
         "only encodes data in base64 without encryption",
         "uses the password directly as the encryption key"),
        ("API key rotation", "issues new keys while temporarily accepting old ones during a grace period, then revoking old keys",
         "changes the key format from UUID to random string",
         "rotates keys every request automatically",
         "only requires changing the key on the client side"),
        ("input validation with Pydantic", "defines schemas with type annotations and validators that reject invalid data before processing",
         "only checks types at import time, not runtime",
         "converts all input to strings for safety",
         "replaces dangerous characters with underscores"),
        ("HTTPS/TLS in Python (ssl module)", "wraps sockets with TLS encryption, verifying server certificates by default",
         "only encrypts the URL path, not the body",
         "requires manual certificate parsing in every request",
         "is only available on Linux systems"),
        ("password reset token security", "uses a cryptographically random token with short expiration and single-use enforcement",
         "emails the user their current password",
         "uses the user ID as the reset token",
         "allows unlimited reset attempts with the same token"),
        ("Content Security Policy (CSP)", "restricts which sources can load scripts/styles/images via HTTP response headers",
         "encrypts all page content automatically",
         "blocks all external CSS files",
         "is configured in the HTML body tag"),
        ("secure session management", "uses HttpOnly, Secure, SameSite cookies with server-side session storage and rotation",
         "stores all session data in a client-side cookie in plaintext",
         "uses URL parameters to track sessions",
         "requires the user to re-authenticate on every page"),
        ("constant-time comparison for secrets", "prevents timing attacks by always comparing all bytes regardless of mismatch position",
         "is faster than regular comparison for long strings",
         "only works for strings shorter than 32 bytes",
         "compares strings character by character from left to right"),
        ("salting passwords before hashing", "adds unique random data per password so identical passwords produce different hashes",
         "adds flavor text to make hashes more readable",
         "uses the username as additional hash input",
         "is unnecessary when using SHA-256"),
        ("OAuth2 PKCE extension", "protects the authorization code flow for public clients using code_verifier and code_challenge",
         "adds password protection to client credentials flow",
         "encrypts the access token with a per-session key",
         "is only used for mobile applications on iOS"),
        ("webhook signature validation", "verifies the HMAC/signature sent in headers matches the computed hash of the payload body",
         "checks that the webhook URL uses HTTPS",
         "validates the webhook sender IP against a whitelist",
         "requires mutual TLS for all webhook deliveries"),
        ("principle of least privilege", "grants each component only the minimum permissions needed for its function",
         "gives admin access to all service accounts for simplicity",
         "uses a single shared credential for all services",
         "restricts access based on time of day only"),
        ("JWT RS256 vs HS256", "RS256 uses asymmetric RSA keys (private signs, public verifies); HS256 uses a shared secret",
         "HS256 is more secure because it uses longer keys",
         "RS256 is faster because RSA operations are simpler",
         "they are interchangeable with no security difference"),
        ("CSRF token protection", "embeds a unique per-session token in forms that the server validates on submission",
         "blocks all POST requests from external sites using CORS",
         "requires re-authentication for every form submission",
         "encrypts form data before submission"),
        ("API gateway authentication", "validates tokens/keys at the gateway level before requests reach backend services",
         "requires each microservice to implement its own auth independently",
         "uses network-level firewall rules instead of application auth",
         "only authenticates the first request in a session"),
        ("secrets.compare_digest(a, b)", "performs constant-time comparison to prevent timing side-channel attacks on secret values",
         "computes a message digest of both strings and compares hashes",
         "is faster than == operator for long strings",
         "only works with bytes objects, not strings"),
        ("environment variable for secrets", "keeps secrets out of source code, loaded at runtime from the deployment environment",
         "encrypts environment variables automatically on disk",
         "is less secure than hardcoding secrets in config files",
         "requires restarting the application when secrets change"),
        ("mTLS (mutual TLS)", "both client and server present certificates, enabling strong mutual authentication",
         "only the client verifies the server certificate",
         "uses two separate TLS connections simultaneously",
         "is the same as standard HTTPS"),
        ("token revocation strategies", "uses a deny-list or short-lived tokens with refresh rotation to limit exposure of compromised tokens",
         "is impossible with JWTs since they are stateless",
         "requires restarting the authentication server",
         "changes the signing key to invalidate all tokens"),
        ("password complexity validation", "enforces minimum length, character variety, and checks against common password databases",
         "only checks that the password is not empty",
         "requires exactly 8 characters with one number",
         "hashes the password first then checks length of the hash"),
        ("HTTP Strict Transport Security (HSTS)", "tells browsers to only use HTTPS for the domain, preventing protocol downgrade attacks",
         "encrypts HTTP requests at the network level",
         "adds authentication headers to all requests",
         "is a server-side firewall configuration"),
        ("API versioning for auth changes", "maintains backward compatibility while migrating auth mechanisms across API versions",
         "requires all clients to update simultaneously",
         "uses different passwords for each API version",
         "is handled automatically by the API gateway"),
    ]:
        base.append({
            "question_text": f"What is correct about {concept} in application security?\n\n  # Implementing in {{FN}}...",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Additional scenario-based questions
    for q, c, w1, w2, w3 in [
        ("You need to store user passwords. Which approach is correct?\n\n  import bcrypt\n  hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=12))",
         "Hash with bcrypt using a high work factor; never store plaintext or use fast hashes like MD5",
         "Store passwords encrypted with AES so they can be recovered if users forget them",
         "Use SHA-256 without salt since it is a secure hash function",
         "Store passwords in a separate database for security through obscurity"),
        ("Your API receives a JWT. What should you verify?\n\n  token = request.headers['Authorization'].split()[1]\n  payload = jwt.decode(token, key, algorithms=['RS256'])",
         "Verify signature, expiration (exp), issuer (iss), audience (aud), and algorithm",
         "Only check that the token is not empty",
         "Verify the token length is at least 100 characters",
         "Only check the expiration time, signature is optional"),
        ("How should you handle failed login attempts?\n\n  # In {{FN}} authentication handler",
         "Implement account lockout or exponential backoff after N failures; log attempts for monitoring",
         "Return different error messages for wrong username vs wrong password",
         "Immediately lock the account permanently after 1 failed attempt",
         "Add a 10-second sleep to the login endpoint for all requests"),
        ("What is the secure way to generate a password reset token?\n\n  import secrets\n  token = secrets.token_urlsafe(32)",
         "Use secrets module for cryptographic randomness, set short expiry, allow single use only",
         "Use random.randint() to generate a 6-digit code with no expiration",
         "Use the user email hashed with MD5 as the token",
         "Use a sequential integer that increments per request"),
        ("How do you prevent SQL injection in this code?\n\n  cursor.execute(f'SELECT * FROM users WHERE name = {name}')",
         "Use parameterized queries: cursor.execute('SELECT * FROM users WHERE name = %s', (name,))",
         "Wrap the variable in quotes: f\"...name = '{name}'\" ",
         "Check that name contains only alphanumeric characters",
         "Limit the name variable to 20 characters maximum"),
        ("What is wrong with: jwt.decode(token, options={'verify_signature': False})?",
         "Disabling signature verification allows any attacker to forge tokens with arbitrary claims",
         "Nothing, this is fine for development environments",
         "It only affects performance, not security",
         "This syntax is invalid and raises an error"),
        ("How should you implement API rate limiting?\n\n  # In middleware for {{FN}}",
         "Use a sliding window or token bucket algorithm per client identifier (IP/API key) with Redis backing",
         "Add a global sleep(0.1) between all requests",
         "Limit total server connections in the OS configuration",
         "Only rate limit unauthenticated requests"),
        ("What is the security issue with storing JWT in localStorage?\n\n  localStorage.setItem('token', jwt_token)",
         "Vulnerable to XSS attacks since JavaScript can access localStorage; prefer HttpOnly cookies",
         "localStorage is too slow for token retrieval",
         "localStorage has a 5KB size limit that JWTs exceed",
         "There is no security issue with this approach"),
        ("Why use constant-time comparison for token validation?\n\n  import hmac\n  hmac.compare_digest(expected, received)",
         "Regular string comparison leaks timing information proportional to matching prefix length",
         "It is required by the HMAC specification",
         "Regular comparison raises exceptions on mismatch",
         "Constant-time comparison is faster for long strings"),
        ("How should sensitive configuration be managed in production?\n\n  # Loading secrets in {{FN}}",
         "Use environment variables or a secrets manager (Vault, AWS SSM); never commit secrets to git",
         "Store secrets in a config.py file with restricted file permissions",
         "Encrypt secrets in the source code using a hardcoded key",
         "Use .env files committed to the repository with gitignore"),
        ("What is the purpose of the 'aud' claim in a JWT?",
         "Specifies the intended recipient/service so tokens cannot be reused across different services",
         "Contains the audience size for analytics",
         "Is an optional decorative field with no security function",
         "Specifies the audio encoding format for multimedia tokens"),
        ("How does OAuth2 prevent token theft in the authorization code flow?",
         "The code is short-lived, single-use, and exchanged server-side with client_secret; PKCE adds more protection",
         "It encrypts all tokens with the user password",
         "It uses two-factor authentication for every token request",
         "It is not designed to prevent token theft"),
        ("What is a timing attack on password comparison?",
         "An attacker measures response times to determine how many characters of their guess match the real password",
         "An attack that tries passwords at specific times of day",
         "A brute-force attack that is timed to avoid rate limiting",
         "An attack on the server clock to bypass token expiration"),
        ("Why should you validate the 'alg' header in JWT verification?\n\n  # jwt.decode(token, key, algorithms=['RS256'])",
         "Prevents algorithm confusion attacks where attacker switches RS256 to HS256 using the public key as secret",
         "Ensures the token was encrypted, not just signed",
         "Validates that the token uses the fastest algorithm",
         "The algorithm header is informational and not security-relevant"),
        ("What is the secure way to handle file uploads?\n\n  # In {{FN}} upload handler",
         "Validate file type by content (magic bytes), limit size, use random names, store outside webroot",
         "Check only the file extension in the filename",
         "Allow all file types but scan with antivirus after upload",
         "Store uploaded files in the same directory as application code"),
    ]:
        base.append({"question_text": q, "correct": c, "w1": w1, "w2": w2, "w3": w3})

    questions = []
    for i in range(count):
        b = base[i % len(base)].copy()
        fn = FUNCS[i % len(FUNCS)]
        questions.append({
            "question_text": b["question_text"].replace("{FN}", fn),
            "option_a": b["correct"].replace("{FN}", fn),
            "option_b": b["w1"].replace("{FN}", fn),
            "option_c": b["w2"].replace("{FN}", fn),
            "option_d": b["w3"].replace("{FN}", fn),
            "correct_answer": "A",
            "difficulty": "advanced",
            "topic": "security_auth",
        })
    return questions

print('gen_security_auth defined')


def gen_system_design(count=500):
    """Generate system design questions."""
    base = []
    for concept, correct, w1, w2, w3 in [
        ("microservices vs monolith", "microservices enable independent deployment and scaling but add network complexity and operational overhead",
         "microservices are always better than monoliths", "monoliths cannot scale horizontally",
         "microservices eliminate the need for databases"),
        ("API gateway pattern", "provides a single entry point handling routing, auth, rate limiting, and protocol translation for backend services",
         "is a database proxy for connection pooling", "replaces all backend services with one service",
         "only handles SSL termination"),
        ("circuit breaker pattern", "stops calling a failing service after threshold failures, allowing it to recover before retrying",
         "physically disconnects network cables when errors occur", "retries failed requests indefinitely until success",
         "is a hardware component in the network switch"),
        ("Redis as a caching layer", "stores frequently accessed data in-memory with O(1) access, reducing database load significantly",
         "is a persistent SQL database replacement", "can only cache string values under 1KB",
         "requires data to be written to Redis before the primary database"),
        ("LRU cache strategy", "evicts the least recently used items when cache capacity is reached, keeping hot data accessible",
         "removes the most recently used items first", "never evicts items once cached",
         "only works for numerical data"),
        ("message queue (Celery/RabbitMQ)", "decouples producers from consumers, enabling async task processing and load leveling",
         "requires synchronous request-response patterns", "stores messages permanently like a database",
         "can only handle one message at a time"),
        ("Redis pub/sub pattern", "enables real-time message broadcasting to multiple subscribers without message persistence",
         "guarantees message delivery even if subscribers are offline", "is the same as a message queue with guaranteed ordering",
         "only supports one subscriber per channel"),
        ("database connection pooling", "maintains pre-established connections to avoid repeated handshake overhead per query",
         "creates a new connection for each query for isolation", "pools query results for reuse across requests",
         "limits total database storage size"),
        ("read replicas pattern", "routes read queries to replicas to scale read throughput while writes go to primary",
         "copies the entire database to every application server", "requires all reads to go through the primary",
         "replicas are always perfectly in sync with no lag"),
        ("event-driven architecture", "components communicate through events, enabling loose coupling and reactive processing",
         "requires all services to use the same programming language", "events must be processed synchronously",
         "is the same as request-response architecture"),
        ("CQRS pattern", "separates read and write models, allowing independent optimization of query and command paths",
         "combines all operations into a single endpoint", "requires eventual consistency for all writes",
         "stands for Create-Query-Read-Store"),
        ("saga pattern for distributed transactions", "coordinates multiple service transactions using a sequence of local transactions with compensating actions on failure",
         "uses a single distributed lock across all services", "requires two-phase commit across all databases",
         "rolls back all services simultaneously using shared memory"),
        ("health check endpoints", "expose service status (dependencies, resources) for load balancers and orchestrators to detect failures",
         "only check if the HTTP server is running", "should include sensitive configuration details for debugging",
         "are only needed in development environments"),
        ("structured logging", "outputs logs as parseable JSON with consistent fields (timestamp, level, correlation_id) for aggregation",
         "logs only error messages to save disk space", "uses free-form text that is easier to read",
         "writes logs directly to the monitoring dashboard"),
        ("OpenTelemetry for observability", "provides unified tracing, metrics, and logging with distributed context propagation across services",
         "only collects CPU and memory metrics", "requires all services to use the same language",
         "replaces all logging with distributed traces"),
        ("blue-green deployment", "maintains two identical environments, switching traffic from blue to green after verification",
         "deploys to half the servers at a time", "uses feature flags instead of separate environments",
         "requires manual DNS changes for every deployment"),
        ("canary deployment", "routes a small percentage of traffic to the new version, gradually increasing if metrics are healthy",
         "deploys to a single canary server that is never used by real users", "is the same as blue-green deployment",
         "requires all users to opt-in to the new version"),
        ("feature flags", "enable runtime toggling of features without deployment, supporting A/B testing and gradual rollouts",
         "are compile-time constants that require redeployment to change", "only work for UI features, not backend logic",
         "are the same as environment variables"),
        ("idempotency in APIs", "ensures repeated identical requests produce the same result, critical for safe retries in distributed systems",
         "means the API only accepts each request once", "requires unique URLs for every request",
         "is only relevant for GET requests"),
        ("webhook delivery system", "implements retry with exponential backoff, signature verification, and delivery status tracking",
         "sends webhooks once without retry and ignores failures", "requires the receiver to poll for new events",
         "uses WebSocket connections for webhook delivery"),
        ("serverless (AWS Lambda) patterns", "executes functions on-demand with automatic scaling and per-invocation billing, best for sporadic workloads",
         "runs continuously like a traditional server", "is always cheaper than containers for all workloads",
         "cannot connect to databases or external services"),
        ("database sharding", "horizontally partitions data across multiple database instances to scale write throughput",
         "creates full copies of the database on each shard", "is the same as read replicas",
         "only works for SQL databases"),
        ("service mesh (e.g., Istio)", "provides infrastructure-level traffic management, mTLS, and observability between services transparently",
         "replaces all API gateways", "requires code changes in every service",
         "only handles east-west traffic, not north-south"),
        ("event sourcing", "stores all state changes as an immutable sequence of events, enabling complete audit trail and temporal queries",
         "is the same as regular CRUD with timestamps", "only stores the current state of entities",
         "requires events to be mutable for corrections"),
        ("back-of-the-envelope capacity estimation", "estimates system requirements (QPS, storage, bandwidth) using rough calculations to guide architecture decisions",
         "requires exact measurements before any design decisions", "is only useful for databases, not services",
         "uses machine learning to predict capacity needs"),
        ("load balancer algorithms", "distribute requests using strategies like round-robin, least-connections, or weighted routing based on server capacity",
         "always send all requests to the fastest server", "only work with HTTP, not TCP",
         "require sticky sessions for all applications"),
        ("distributed cache invalidation", "uses TTL, event-driven invalidation, or versioned keys to ensure cache consistency across nodes",
         "is impossible in distributed systems", "requires stopping all services to clear caches",
         "only matters for write-heavy workloads"),
        ("graceful shutdown", "stops accepting new requests, completes in-flight requests, closes connections, then exits cleanly",
         "kills the process immediately with SIGKILL", "only matters for stateful services",
         "requires draining all database connections first"),
        ("retry with exponential backoff", "increases delay between retries exponentially with jitter to avoid thundering herd on recovering services",
         "retries immediately without any delay", "uses a fixed 1-second delay between all retries",
         "only retries once then gives up permanently"),
        ("database migration strategies", "applies versioned schema changes incrementally, supporting rollback, with zero-downtime techniques like expand-contract",
         "drops and recreates the entire database on each deployment", "requires application downtime for any schema change",
         "only works with NoSQL databases"),
        ("rate limiting algorithms (token bucket)", "allows burst traffic up to bucket capacity while maintaining a steady average rate of requests",
         "blocks all requests once the limit is reached until the next day", "counts only POST requests toward the limit",
         "uses a fixed window that resets at midnight UTC"),
        ("correlation ID for request tracing", "propagates a unique ID through all services handling a request, enabling end-to-end debugging",
         "is generated separately by each service", "is only used in error responses",
         "is the same as a session cookie"),
        ("bulkhead pattern", "isolates components so failure in one does not cascade (e.g., separate thread pools per dependency)",
         "adds extra servers as backup for failures", "is a physical network isolation technique",
         "requires all services to share resources for efficiency"),
        ("sidecar pattern", "deploys auxiliary functionality (logging, proxy, config) as a companion process alongside the main service",
         "runs all features in a single process for simplicity", "is a client-side only pattern",
         "requires modifying the main service code"),
        ("CDC (Change Data Capture)", "captures database changes as events for downstream systems, enabling real-time data synchronization",
         "is a batch ETL process that runs daily", "only works with MongoDB",
         "requires manual triggers in application code"),
    ]:
        base.append({
            "question_text": f"In system design, what is true about {concept}?\n\n  # Implementing in {{FN}} service...",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Extra scenario questions
    for q, c, w1, w2, w3 in [
        ("Your API is receiving 10x normal traffic. What is the first architectural mitigation?",
         "Add caching (Redis/CDN) for repeated reads and auto-scale horizontally behind a load balancer",
         "Add more RAM to the single server until it can handle the load",
         "Switch from REST to GraphQL which is inherently faster",
         "Rewrite the application in a faster language like Rust"),
        ("A microservice is failing intermittently. How do you prevent cascade failures?",
         "Implement circuit breaker, timeouts, and bulkhead patterns to isolate the failure",
         "Increase the timeout to 60 seconds so requests eventually succeed",
         "Merge all microservices into a monolith to eliminate network failures",
         "Add unlimited retries until the service recovers"),
        ("You need to process 1M events per hour reliably. What architecture fits?",
         "Event-driven with message queue (Kafka/RabbitMQ), consumer groups, and at-least-once delivery",
         "Synchronous REST API with a for loop processing each event sequentially",
         "Store events in a CSV file and process nightly with a cron job",
         "Use WebSockets to stream all events to a single consumer"),
        ("How do you ensure data consistency across microservices without distributed transactions?",
         "Use the saga pattern with compensating transactions and eventual consistency",
         "Use a global database shared by all services",
         "Implement two-phase commit across all services",
         "Make all operations synchronous with distributed locks"),
        ("Your Redis cache has a 95% hit rate but a cache stampede occurs on expiry. How do you fix it?",
         "Use cache warming, probabilistic early expiration, or locking to prevent simultaneous regeneration",
         "Increase cache TTL to infinity so items never expire",
         "Add more Redis nodes to handle the stampede load",
         "Switch to database-only access without any caching"),
        ("How should you handle partial failures in an API that calls 3 downstream services?",
         "Return partial results with degraded status, use timeouts per service, and have fallbacks for non-critical data",
         "Fail the entire request if any downstream service is unavailable",
         "Cache all downstream responses and never make real calls",
         "Retry all three services indefinitely until all succeed"),
        ("You need to migrate a monolith to microservices. What is the recommended approach?",
         "Strangler fig pattern: incrementally extract services starting with clear domain boundaries",
         "Rewrite everything from scratch in parallel with the existing system",
         "Split by database tables, one service per table",
         "Convert each class to its own microservice"),
        ("How do you implement exactly-once processing in a distributed system?",
         "Use idempotency keys with deduplication: at-least-once delivery combined with idempotent consumers",
         "Use TCP which guarantees exactly-once delivery",
         "Configure the message broker for exactly-once mode (which all brokers support)",
         "Exactly-once is automatic with any REST API"),
        ("What strategy ensures zero-downtime database migrations?",
         "Expand-contract: add new columns/tables first, migrate code, then remove old schema",
         "Take the application offline during migration for consistency",
         "Use ALTER TABLE commands which are always non-blocking",
         "Only add indexes; never change column types or names"),
        ("How do you design a system that handles 10K concurrent WebSocket connections?",
         "Use async framework (asyncio/Go), connection manager with pub/sub backend (Redis), and horizontal scaling with sticky sessions",
         "Use one thread per connection with threading",
         "Store all messages in a SQL database and poll every second",
         "Use long-polling HTTP instead of actual WebSockets"),
    ]:
        base.append({"question_text": q, "correct": c, "w1": w1, "w2": w2, "w3": w3})

    questions = []
    for i in range(count):
        b = base[i % len(base)].copy()
        fn = FUNCS[i % len(FUNCS)]
        questions.append({
            "question_text": b["question_text"].replace("{FN}", fn),
            "option_a": b["correct"].replace("{FN}", fn),
            "option_b": b["w1"].replace("{FN}", fn),
            "option_c": b["w2"].replace("{FN}", fn),
            "option_d": b["w3"].replace("{FN}", fn),
            "correct_answer": "A",
            "difficulty": "advanced",
            "topic": "system_design",
        })
    return questions

print('gen_system_design defined')


def gen_mixed_advanced(count=500):
    """Generate mixed advanced Python questions."""
    base = []
    for concept, correct, w1, w2, w3 in [
        ("combining decorators with async functions", "use functools.wraps and ensure the wrapper is also async, preserving coroutine behavior",
         "decorators cannot be used with async functions in Python", "the decorator must use threading internally",
         "only class-based decorators work with async"),
        ("metaclass __init_subclass__ hook", "is called on the parent class when a subclass is defined, enabling registration or validation without a metaclass",
         "is called when an instance is created", "only works with abstract base classes",
         "is deprecated in favor of __class_getitem__"),
        ("descriptor protocol (__get__, __set__, __delete__)", "enables reusable attribute access logic; descriptors defined on the class control instance attribute behavior",
         "only works for class attributes, not instance attributes", "requires metaclasses to function",
         "is the same as property() with no advantages"),
        ("Protocol classes (structural subtyping)", "enable duck typing with static type checking - classes match if they have the required methods, no inheritance needed",
         "require explicit inheritance from the Protocol class", "only work at runtime, not with type checkers",
         "are the same as ABCs (Abstract Base Classes)"),
        ("Generic types with TypeVar bounds", "allow type-safe code that works with multiple types while constraining to specific interfaces",
         "create new types at runtime through code generation", "are only for container types like List and Dict",
         "require runtime type checking with isinstance"),
        ("Pydantic model validation", "validates data at runtime using type annotations, providing coercion, custom validators, and serialization",
         "only validates types at import time using mypy", "requires manual validation code in __init__",
         "is identical to dataclasses with no extra features"),
        ("FastAPI dependency injection", "uses Depends() to declare reusable dependencies that are resolved per-request with proper cleanup via yield",
         "requires a separate DI framework like inject", "only works for database connections",
         "creates global singletons for all dependencies"),
        ("SQLAlchemy async sessions", "use async_sessionmaker and AsyncSession with await for queries, requiring an async engine",
         "are identical to synchronous sessions with no code changes needed", "cannot use relationship lazy loading",
         "require running in a separate thread automatically"),
        ("Python contextvar for request context", "provides task-local storage that correctly propagates across async tasks in the same context",
         "is the same as threading.local() for async code", "only works in synchronous functions",
         "requires manual propagation to each new task"),
        ("combining OOP with API integration", "use service classes that encapsulate API client logic with retry, circuit breaker, and structured error handling",
         "API calls should always be in standalone functions, never in classes",
         "each API endpoint needs its own class", "OOP patterns do not apply to HTTP communication"),
        ("async context managers (__aenter__, __aexit__)", "enable resource management with async setup/teardown using 'async with' syntax",
         "are the same as regular context managers with no differences", "cannot be used with asyncio",
         "require the class to inherit from AsyncContextManager"),
        ("error handling in data pipelines", "use structured error collection, dead letter queues, and partial failure handling to avoid all-or-nothing processing",
         "stop the entire pipeline on the first error", "silently skip all errors and continue",
         "log errors but never retry or alert"),
        ("testing async code with pytest", "use pytest-asyncio with @pytest.mark.asyncio decorator and async test functions, or anyio for backend-agnostic tests",
         "async tests run synchronously with asyncio.run() in each test", "pytest cannot test async code natively",
         "use threading to run the event loop in tests"),
        ("__slots__ for memory optimization", "prevents __dict__ creation per instance, reducing memory for many instances but disabling dynamic attributes",
         "makes attribute access faster but uses more memory", "only works with dataclasses",
         "is identical to using __dict__ with no real benefit"),
        ("weakref for avoiding circular references", "allows referencing objects without preventing garbage collection, useful for caches and observer patterns",
         "makes all references weak by default in Python", "only works for built-in types",
         "prevents any garbage collection of the referenced object"),
        ("typing.overload for multiple signatures", "provides type checker hints for functions that return different types based on input, not runtime dispatch",
         "enables actual runtime method overloading like Java", "is required for default parameter values",
         "replaces the need for Union return types entirely"),
        ("dataclass field() with default_factory", "provides a factory function called per-instance to avoid the mutable default argument pitfall",
         "is only needed for string fields", "creates a class-level shared default",
         "is the same as setting default=[] directly"),
        ("ABC with abstractmethod enforcement", "prevents instantiation of classes that do not implement all abstract methods, enforced at class creation time",
         "raises an error only when the abstract method is called", "is purely a documentation convention with no enforcement",
         "requires metaclass=ABCMeta on every subclass"),
        ("async generator (async for)", "yields values asynchronously, allowing await inside the generator body for I/O operations between yields",
         "is identical to a regular generator wrapped in a coroutine", "cannot use yield and await in the same function",
         "requires manual __aiter__ and __anext__ implementation"),
        ("functools.singledispatch", "provides single-dispatch generic functions, dispatching on the type of the first argument at runtime",
         "dispatches on all argument types simultaneously", "only works with class methods",
         "is the same as if/elif isinstance() chains with no advantage"),
        ("Python memory management with gc module", "uses reference counting plus cyclic garbage collector; gc.collect() can force collection of reference cycles",
         "uses only mark-and-sweep like Java", "never automatically frees memory; gc.collect() is required",
         "reference counting handles all cases including cycles automatically"),
        ("type narrowing with TypeGuard", "tells the type checker that if the function returns True, the argument is of the narrowed type",
         "performs runtime type conversion automatically", "is the same as cast() with runtime checking",
         "only works with Union types of exactly two members"),
        ("Pydantic validator decorator (@validator/@field_validator)", "runs custom validation logic on individual fields with access to field value and optionally other fields",
         "only validates after the model is fully constructed", "replaces type annotation checking entirely",
         "cannot raise ValidationError for custom messages"),
        ("FastAPI background tasks", "execute after the response is sent, useful for non-critical operations like emails or logging without blocking the response",
         "block the response until they complete", "run in a separate process always",
         "cannot access request data or dependencies"),
        ("SQLAlchemy hybrid_property", "works both as a Python property on instances and as a SQL expression in queries",
         "only works in SQL queries, not on Python instances", "is the same as @property with no SQL support",
         "requires raw SQL strings to function"),
        ("Docker multi-stage builds for Python", "use a build stage for dependencies/compilation and a slim runtime stage, reducing final image size significantly",
         "are slower than single-stage builds", "require copying the entire source tree to every stage",
         "only work for compiled languages, not Python"),
        ("CI/CD pipeline testing stages", "run unit tests, then integration tests, then acceptance tests in sequence, failing fast on earlier stages",
         "run all test types simultaneously for speed", "only need unit tests in CI; other tests are manual",
         "should deploy first then run tests on production"),
        ("profiling Python code with cProfile", "measures function call counts and cumulative time to identify performance bottlenecks",
         "only profiles memory usage, not execution time", "requires modifying every function to add timing code",
         "is too slow to use and should be replaced with print statements"),
        ("Python GC generational collection", "uses three generations; new objects start in gen 0, surviving objects promote to older generations collected less frequently",
         "has only one generation that is collected on every allocation", "older objects are collected more frequently than new ones",
         "generational collection is disabled by default in CPython"),
        ("contextlib.asynccontextmanager", "creates async context managers from async generator functions using yield, simplifying __aenter__/__aexit__",
         "converts synchronous context managers to async automatically", "only works with file I/O operations",
         "requires two yield statements (one for enter, one for exit)"),
        ("Python structural pattern matching (match/case)", "matches objects by structure (attributes, sequences, mappings) with destructuring and guard clauses",
         "is identical to switch/case in C with only literal matching", "requires __match_args__ on all classes",
         "cannot match dictionary patterns"),
        ("dependency injection without a framework", "pass dependencies as constructor/function parameters, making code testable with mock objects",
         "use global variables and import-time initialization for all dependencies",
         "always use a DI container even for small applications",
         "dependency injection is only useful in Java, not Python"),
        ("asyncio.TaskGroup (Python 3.11+)", "provides structured concurrency where all tasks complete or all are cancelled on first error (ExceptionGroup)",
         "is the same as asyncio.gather() with no behavioral differences",
         "does not propagate exceptions from child tasks",
         "runs tasks sequentially, not concurrently"),
        ("Python dataclass post_init processing", "__post_init__ runs after __init__, allowing computed fields and validation based on multiple init fields",
         "runs before __init__ to prepare default values", "is only called when no arguments are passed",
         "replaces __init__ entirely and receives raw kwargs"),
        ("parametrize in pytest", "runs the same test function with multiple sets of inputs, generating separate test cases for each",
         "creates parameterized fixtures that inject random values",
         "only works with integer parameters",
         "requires a separate test file for each parameter set"),
    ]:
        base.append({
            "question_text": f"What is correct about {concept}?\n\n  # Example in {{FN}} implementation",
            "correct": f"It {correct}" if not correct[0].isupper() else correct,
            "w1": f"It {w1}" if not w1[0].isupper() else w1,
            "w2": f"It {w2}" if not w2[0].isupper() else w2,
            "w3": f"It {w3}" if not w3[0].isupper() else w3,
        })

    # Scenario questions
    for q, c, w1, w2, w3 in [
        ("You need to make a decorator that works on both sync and async functions. What approach is correct?\n\n  # Decorating {{FN}}",
         "Check if the wrapped function is a coroutine function with asyncio.iscoroutinefunction() and create appropriate wrapper",
         "Always use an async wrapper since it works for both sync and async",
         "Use threading to convert sync functions to async inside the decorator",
         "Decorators inherently work with both; no special handling is needed"),
        ("How do you test a function that depends on an external API?\n\n  # Testing {{FN}}",
         "Use unittest.mock.patch or responses library to mock HTTP calls with controlled responses",
         "Always make real API calls in tests for accuracy",
         "Skip testing functions that call external APIs",
         "Use time.sleep() to wait for the API to be available"),
        ("What is the correct way to handle database transactions in async SQLAlchemy?\n\n  # In {{FN}}",
         "Use async with session.begin() for automatic commit/rollback, or manual commit() in a try/except",
         "Async SQLAlchemy auto-commits every query so transactions are not needed",
         "Wrap the entire request lifecycle in a single transaction regardless of operations",
         "Use synchronous session for transactions since async does not support them"),
        ("How should you structure error handling in a FastAPI application?\n\n  # Handler for {{FN}}",
         "Use exception handlers for HTTP errors, custom exception classes for domain errors, and structured error responses",
         "Catch all exceptions with bare except and return 500 for everything",
         "Let all exceptions propagate to the default error handler without custom handling",
         "Use assertions for input validation since they raise appropriate HTTP errors"),
        ("Your Python service uses 2GB of memory but should use 500MB. What do you investigate?\n\n  # Profiling {{FN}}",
         "Use tracemalloc or memory_profiler to find allocation hotspots; check for reference cycles, caches without eviction, and large data structures",
         "Increase the server RAM to 4GB to accommodate the usage",
         "Set a memory limit in Python configuration to cap at 500MB",
         "Rewrite the entire service in C for better memory efficiency"),
        ("How do you implement retry logic for a flaky external service call?\n\n  # In {{FN}}",
         "Use tenacity or custom decorator with exponential backoff, max retries, and specific exception types to retry",
         "Use a while True loop that retries until success",
         "Implement retry at the DNS level for all network calls",
         "Cache the last successful response and return it on failures indefinitely"),
    ]:
        base.append({"question_text": q, "correct": c, "w1": w1, "w2": w2, "w3": w3})

    questions = []
    for i in range(count):
        b = base[i % len(base)].copy()
        fn = FUNCS[i % len(FUNCS)]
        questions.append({
            "question_text": b["question_text"].replace("{FN}", fn),
            "option_a": b["correct"].replace("{FN}", fn),
            "option_b": b["w1"].replace("{FN}", fn),
            "option_c": b["w2"].replace("{FN}", fn),
            "option_d": b["w3"].replace("{FN}", fn),
            "correct_answer": "A",
            "difficulty": "advanced",
            "topic": "mixed_advanced",
        })
    return questions

print('gen_mixed_advanced defined')


def gen_devops_deployment(count=500):
    """Generate DevOps and deployment questions."""
    base = []
    for concept, correct, w1, w2, w3 in [
        ("Docker multi-stage build", "uses multiple FROM statements to separate build dependencies from the final slim runtime image",
         "copies all build tools into the final image", "requires a separate Dockerfile per stage",
         "is slower than a single-stage build in all cases"),
        ("Docker layer caching", "reuses unchanged layers from previous builds; ordering commands from least to most frequently changing maximizes cache hits",
         "caches the entire image as one unit regardless of layer order", "only caches the final layer",
         "requires manual cache invalidation for each build"),
        ("COPY vs ADD in Dockerfile", "COPY is preferred for local files; ADD auto-extracts tar archives and supports URLs but is less predictable",
         "ADD is always preferred because it is more powerful", "COPY and ADD are completely identical",
         "ADD is deprecated and should never be used"),
        (".dockerignore file", "excludes files from the build context, reducing image size and preventing secrets from being copied",
         "ignores files during container runtime", "is the same as .gitignore with no differences",
         "only affects the COPY command, not ADD"),
        ("Docker HEALTHCHECK instruction", "defines a command the Docker daemon runs periodically to check container health status",
         "monitors host machine health, not container health", "is only used by Docker Compose, not standalone Docker",
         "replaces the need for application-level health endpoints"),
        ("Docker volumes vs bind mounts", "volumes are managed by Docker for persistent data; bind mounts map host paths directly into containers",
         "volumes and bind mounts are identical in behavior", "bind mounts are more portable across hosts",
         "volumes cannot persist data across container restarts"),
        ("Docker networking (bridge vs host)", "bridge creates isolated networks between containers; host shares the host network stack directly",
         "bridge mode shares the host network; host mode is isolated", "all containers always share the same network",
         "networking only works between containers on the same physical host"),
        ("reducing Docker image size", "use slim/alpine base images, combine RUN commands, remove package manager caches, use multi-stage builds",
         "image size does not affect deployment or performance", "always use the latest Ubuntu as base for completeness",
         "splitting RUN commands makes images smaller due to layer deduplication"),
        ("GitHub Actions workflow triggers", "can trigger on push, pull_request, schedule (cron), workflow_dispatch (manual), and many other events",
         "can only trigger on push events to the main branch", "require manual triggering for every run",
         "do not support cron-based scheduled execution"),
        ("GitHub Actions job matrix", "runs the same job with multiple configurations (Python versions, OS) in parallel, testing combinations",
         "runs all configurations sequentially on a single runner", "only supports operating system variation",
         "requires separate workflow files for each configuration"),
        ("GitHub Actions caching (actions/cache)", "caches dependencies (pip, node_modules) between runs, speeding up workflows by avoiding re-downloads",
         "caches the entire Docker image for the runner", "automatically caches all files in the workspace",
         "is only available for paid GitHub plans"),
        ("GitHub Actions secrets", "store sensitive values encrypted, accessible only during workflow runs via secrets context, never logged",
         "are stored in plaintext in the workflow YAML file", "are visible to anyone with read access to the repository",
         "can only store strings shorter than 64 characters"),
        ("CI pipeline testing stages (unit -> integration -> e2e)", "run fast tests first, failing early before expensive tests, providing quick feedback",
         "always run all test types simultaneously for speed", "only unit tests belong in CI; integration tests are manual",
         "e2e tests should run before unit tests to catch real bugs first"),
        ("AWS Lambda cold start", "occurs on first invocation or after idle period, adding latency for container initialization and code loading",
         "happens on every single invocation regardless of frequency", "only affects Java functions, not Python",
         "is eliminated entirely by provisioned concurrency in all cases"),
        ("AWS Lambda layers", "package shared dependencies separately from function code, reusable across functions and reducing deployment size",
         "are a networking feature for connecting Lambda to VPCs", "store function execution logs",
         "are required for all Lambda functions"),
        ("serverless function timeout handling", "set appropriate timeouts (max 15min for Lambda); design for short execution with async patterns for long tasks",
         "serverless functions have no timeout limit", "timeouts restart the function automatically",
         "only applies to synchronous invocations"),
        ("environment management (dev/staging/prod)", "use separate configurations per environment with infrastructure-as-code ensuring consistency",
         "use the same database for all environments to ensure consistency", "only production needs its own environment",
         "manually configure each environment differently based on need"),
        ("structured logging in production", "output JSON logs with consistent fields (timestamp, level, request_id, service) for machine parsing and aggregation",
         "use print() statements for simplicity and readability", "log only errors to minimize log storage costs",
         "use different log formats for each service to identify the source"),
        ("container health checks in orchestration", "liveness probes detect stuck containers (restart); readiness probes control traffic routing (remove from LB)",
         "liveness and readiness probes serve the same purpose", "probes should always check external dependencies",
         "health checks are only needed during initial deployment"),
        ("rolling update deployment strategy", "gradually replaces old pods/containers with new ones, maintaining availability but requiring backward-compatible changes",
         "replaces all instances simultaneously for consistency", "requires manual intervention to proceed at each step",
         "is only available in Kubernetes, not Docker Swarm"),
        ("infrastructure as code (Terraform/Pulumi)", "defines infrastructure declaratively in code, enabling version control, review, reproducibility, and drift detection",
         "requires manual configuration through cloud console after defining specs",
         "only manages compute resources, not networking or storage",
         "runs infrastructure configuration at application startup"),
        ("container orchestration readiness", "ensures containers pass health checks before receiving traffic, preventing requests to uninitialized services",
         "starts sending traffic immediately on container creation", "only checks that the container process is running",
         "waits a fixed 60 seconds regardless of actual readiness"),
        ("Docker Compose for local development", "defines multi-container applications with networking, volumes, and environment in a single YAML file",
         "is a production-ready orchestration tool replacing Kubernetes", "only works with a single container",
         "requires root access on the host machine"),
        ("CI/CD artifact management", "builds artifacts once, promotes same artifact through environments, ensuring what was tested is what gets deployed",
         "rebuilds the application from source in each environment", "stores artifacts in the git repository",
         "only applies to compiled languages, not Python"),
        ("feature branch deployment (preview environments)", "creates temporary environments for each PR, enabling testing and review before merging to main",
         "deploys every commit to production immediately", "only works with trunk-based development",
         "requires manual environment provisioning for each branch"),
        ("container resource limits (CPU/memory)", "prevent runaway containers from consuming all host resources, enabling fair sharing and predictable performance",
         "are only suggestions that containers can exceed", "slow down containers artificially",
         "only apply to memory, not CPU"),
        ("monitoring with Prometheus + Grafana", "Prometheus scrapes metrics endpoints at intervals; Grafana visualizes time-series data with dashboards and alerts",
         "Prometheus stores logs; Grafana stores metrics", "they require a paid license for production use",
         "only monitor infrastructure, not application-level metrics"),
        ("GitOps workflow (ArgoCD/Flux)", "uses Git as single source of truth for infrastructure; changes to git repo trigger automated reconciliation",
         "requires manual kubectl commands after each git push", "only works with GitHub, not GitLab",
         "is the same as traditional CI/CD with no differences"),
        ("blue-green with database migrations", "requires backward-compatible migrations since both versions run simultaneously during switchover",
         "automatically migrates the database during the switch", "uses separate databases for blue and green",
         "does not support database changes"),
        ("container logging best practices", "write logs to stdout/stderr; let the orchestrator handle collection, aggregation, and storage",
         "write logs to files inside the container for persistence", "use syslog for all container logging",
         "disable logging in containers for performance"),
        ("deployment rollback strategies", "keep previous version ready (blue-green) or use container image tags to quickly redeploy the last known good version",
         "rollback requires rerunning the entire CI/CD pipeline for the old version",
         "version control (git revert) is the only rollback mechanism",
         "rollbacks are not possible with container deployments"),
        ("secrets management in containers", "inject secrets at runtime via environment variables or mounted volumes from a secrets manager (Vault, AWS SSM)",
         "bake secrets into the container image at build time", "store secrets in the Docker Compose file",
         "hardcode secrets in application configuration files"),
        ("Python dependency pinning for reproducible builds", "use pip freeze or pip-tools to pin exact versions including transitive dependencies",
         "use >= version constraints for maximum compatibility", "never pin versions to always get security updates",
         "pinning is only needed for production, not development"),
        ("serverless cold start mitigation", "use provisioned concurrency, minimize package size, lazy imports, and keep functions warm with scheduled pings",
         "cold starts cannot be mitigated in any way", "use larger memory allocations which do not affect cold start",
         "switch to containers which never have cold starts"),
        ("container image security scanning", "scans base images and dependencies for known CVEs, blocking deployment of images with critical vulnerabilities",
         "only checks for malware, not vulnerabilities", "is performed once at build time and never again",
         "requires manual review of each vulnerability with no automation"),
    ]:
        base.append({
            "question_text": f"In DevOps/deployment, what is true about {concept}?\n\n  # Configuring for {{FN}} service",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Scenario questions
    for q, c, w1, w2, w3 in [
        ("Your Docker image is 2GB. How do you reduce it?\n\n  # Image for {{FN}} service",
         "Use multi-stage build with slim base, minimize layers, remove build deps, use .dockerignore",
         "Use a larger base image so dependencies are pre-installed",
         "Split into 10 smaller images that are composed at runtime",
         "Compress the image with gzip after building"),
        ("A GitHub Actions workflow takes 45 minutes. How do you speed it up?\n\n  # CI for {{FN}}",
         "Cache dependencies, parallelize jobs with matrix, skip unnecessary steps with path filters, use faster runners",
         "Remove all tests from the pipeline for speed",
         "Run the workflow weekly instead of on every push",
         "Use a self-hosted runner with no resource limits"),
        ("Your Lambda function times out after 30 seconds processing a large file. What do you do?\n\n  # {{FN}} Lambda",
         "Break work into smaller chunks using Step Functions or SQS; increase timeout if processing time is legitimate",
         "Increase the timeout to 15 minutes and hope it finishes",
         "Convert to a regular EC2 server for unlimited execution time",
         "Process the file synchronously in the API response"),
        ("How do you handle database migrations in a CI/CD pipeline?\n\n  # Migration for {{FN}}",
         "Run migrations as a separate step before deploying new code; ensure backward compatibility for zero-downtime",
         "Apply migrations manually by a DBA before each release",
         "Include migrations in the application startup code",
         "Drop and recreate tables with each deployment"),
        ("Your containerized service crashes under load. What monitoring do you implement?\n\n  # Monitoring {{FN}}",
         "Add resource metrics (CPU/memory), request latency percentiles, error rates, and set alerts on anomalies",
         "Add a print statement for each request to track volume",
         "Monitor only the host machine, not individual containers",
         "Wait for user complaints to identify issues"),
    ]:
        base.append({"question_text": q, "correct": c, "w1": w1, "w2": w2, "w3": w3})

    questions = []
    for i in range(count):
        b = base[i % len(base)].copy()
        fn = FUNCS[i % len(FUNCS)]
        questions.append({
            "question_text": b["question_text"].replace("{FN}", fn),
            "option_a": b["correct"].replace("{FN}", fn),
            "option_b": b["w1"].replace("{FN}", fn),
            "option_c": b["w2"].replace("{FN}", fn),
            "option_d": b["w3"].replace("{FN}", fn),
            "correct_answer": "A",
            "difficulty": "advanced",
            "topic": "devops_deployment",
        })
    return questions

print('gen_devops_deployment defined')


def gen_performance_optimization(count=500):
    """Generate performance optimization questions."""
    base = []
    for concept, correct, w1, w2, w3 in [
        ("cProfile for function profiling", "measures call count, total time, and cumulative time per function to identify bottlenecks",
         "only measures memory usage per function", "requires modifying source code with timing decorators",
         "is too inaccurate for production code analysis"),
        ("line_profiler (@profile)", "shows execution time for each line of a function, revealing hotspots within functions",
         "profiles all lines in the entire codebase simultaneously", "only works with compiled Python (.pyc)",
         "measures memory per line, not execution time"),
        ("memory_profiler for RAM analysis", "shows memory usage change line-by-line, identifying allocation hotspots",
         "only reports total process memory, not per-line", "requires restarting the application between measurements",
         "only works on Linux systems"),
        ("gc module for garbage collection tuning", "allows disabling GC, adjusting thresholds, and identifying reference cycles with gc.get_referrers()",
         "controls CPU garbage collection (unused instruction caching)", "must be enabled explicitly since Python has no default GC",
         "only collects garbage from global variables"),
        ("weakref for cache implementation", "allows cached objects to be garbage collected when no strong references exist, preventing memory leaks",
         "makes all references in the cache stronger to prevent eviction", "is slower than regular dict for all operations",
         "only works with hashable objects"),
        ("__slots__ memory optimization", "eliminates per-instance __dict__, saving ~50-100 bytes per instance for classes with many instances",
         "makes attribute access 10x faster but uses more memory", "is incompatible with inheritance",
         "only saves memory for classes with more than 100 attributes"),
        ("functools.lru_cache", "caches function results based on arguments with O(1) lookup, configurable maxsize, and LRU eviction",
         "caches results to disk for persistence across restarts", "only caches the last single result",
         "works with unhashable arguments like lists and dicts"),
        ("generator pipelines for memory efficiency", "process items one at a time through chained generators, keeping only one item in memory per stage",
         "are slower than loading everything into memory due to yield overhead", "cannot be chained together",
         "require the entire input to be loaded before processing begins"),
        ("lazy evaluation with __getattr__", "defers expensive computation until the attribute is actually accessed, avoiding upfront cost",
         "makes all attribute access lazy by default in Python", "is the same as using @property with no differences",
         "prevents attributes from being cached once computed"),
        ("connection pool sizing", "set pool size based on: connections = (core_count * 2) + disk_spindles; too many causes context switching overhead",
         "always set pool size to the maximum allowed by the database", "pool size should equal the number of concurrent users",
         "one connection is always sufficient if queries are fast enough"),
        ("batch processing vs individual operations", "reduces per-operation overhead (network roundtrips, transaction costs) by grouping multiple items",
         "is always slower due to larger payload processing time", "only matters for write operations, not reads",
         "requires exactly 1000 items per batch for efficiency"),
        ("asyncio performance for I/O-bound workloads", "handles thousands of concurrent connections with a single thread, minimizing memory and context-switch overhead",
         "is always faster than threading for all workload types", "uses more memory than threading per connection",
         "requires multiple CPU cores to be effective"),
        ("database query optimization with EXPLAIN", "reveals the query execution plan, showing index usage, join strategies, and estimated costs for optimization",
         "automatically optimizes the query without manual intervention", "only works for SELECT queries",
         "shows the exact execution time but not the plan"),
        ("indexing strategy for databases", "creates B-tree (or hash) indexes on frequently queried columns, trading write speed for read performance",
         "indexing every column gives the best performance", "indexes only speed up write operations",
         "indexes are automatically created on all columns in modern databases"),
        ("N+1 query problem", "occurs when ORM lazy-loads related objects in a loop; fix with eager loading (joinedload/selectinload)",
         "is a networking protocol error with no database relation", "only happens with raw SQL, not ORMs",
         "is always the fastest approach for small datasets"),
        ("Python string concatenation performance", "joining a list of strings with str.join() is O(n); repeated += is O(n^2) due to string immutability",
         "+= is optimized in CPython and is always the fastest approach", "string concatenation performance does not matter for any realistic workload",
         "f-strings are slower than concatenation for all cases"),
        ("dict comprehension vs loop performance", "comprehensions are slightly faster due to optimized bytecode and reduced name lookups in the loop body",
         "comprehensions are always slower due to creating a temporary list", "there is no measurable difference ever",
         "loops are faster because they avoid function call overhead"),
        ("numpy vs pure Python for numerical computation", "numpy operates on contiguous memory arrays with C-level loops, often 10-100x faster than Python loops",
         "numpy is slower for arrays smaller than 10 million elements", "numpy uses the same Python bytecode internally",
         "pure Python loops are faster when using list comprehensions"),
        ("multiprocessing.Pool for CPU-bound work", "distributes CPU-intensive work across processes, achieving true parallelism by bypassing the GIL",
         "is slower than threading for CPU-bound work due to serialization overhead", "shares the GIL across all pool workers",
         "only works for I/O-bound tasks"),
        ("async database drivers (asyncpg)", "provide non-blocking database access, allowing the event loop to handle other requests while waiting for query results",
         "are always faster than synchronous drivers for single queries", "require a separate connection per concurrent query",
         "bypass the database connection limit"),
        ("object pooling pattern", "reuses expensive-to-create objects (connections, parsers) instead of creating new ones, reducing allocation overhead",
         "creates new objects but pools the memory for faster allocation", "only works for immutable objects",
         "increases memory usage with no performance benefit"),
        ("sys.intern() for string deduplication", "ensures identical strings share the same memory object, useful for repeated lookups in dictionaries",
         "compresses strings to use less memory per character", "is automatically applied to all strings in Python 3",
         "only works for strings shorter than 8 characters"),
        ("__contains__ vs linear search", "sets and dicts provide O(1) __contains__ (hash lookup); lists require O(n) linear scan",
         "lists are faster for __contains__ due to cache locality", "all containers have O(1) lookup in Python",
         "the difference is only noticeable for collections over 1 million items"),
        ("avoiding global variable lookups", "local variable access is faster than global in CPython due to LOAD_FAST vs LOAD_GLOBAL bytecode instructions",
         "global variables are faster because they are cached in a special table", "there is no performance difference between local and global",
         "this only matters in Python 2, not Python 3"),
        ("timeit module for micro-benchmarks", "runs code snippets multiple times to get reliable timing, minimizing noise from system activity",
         "measures wall-clock time of a single execution", "only works in interactive Python shell",
         "is less accurate than time.time() for benchmarking"),
        ("deque vs list for queue operations", "deque provides O(1) append/pop from both ends; list pop(0) is O(n) due to element shifting",
         "list is faster for all queue operations due to simpler implementation", "deque is only faster for random access",
         "they have identical performance characteristics"),
        ("pre-allocating lists vs append", "[None] * n then filling is faster than repeated append due to avoiding resize operations",
         "append is always faster due to dynamic array optimization", "pre-allocation wastes memory and is never worthwhile",
         "Python automatically pre-allocates for append operations"),
        ("reducing function call overhead", "inline small helper functions in hot loops; use built-in functions (map, filter) which avoid Python call overhead",
         "function calls have zero overhead in Python 3", "always wrap code in functions for better performance due to local scope",
         "reduce overhead by using global functions instead of methods"),
        ("async gather vs sequential awaits", "gather runs all coroutines concurrently; sequential awaits wait for each to complete before starting the next",
         "they are identical in performance since Python is single-threaded", "sequential awaits are faster due to less scheduling overhead",
         "gather creates threads for each coroutine"),
        ("Redis pipeline for batch operations", "sends multiple commands in one network roundtrip, reducing latency from N roundtrips to 1",
         "executes commands in parallel on the Redis server", "is identical to sending commands individually in terms of performance",
         "only works for GET operations, not SET"),
        ("Python slots with dataclass", "combine @dataclass(slots=True) (Python 3.10+) for both ergonomic class definition and memory optimization",
         "dataclasses always use __slots__ by default", "slots=True makes dataclasses immutable",
         "this feature is only planned for Python 4.0"),
        ("iterator protocol memory efficiency", "iterators yield one item at a time without storing the entire sequence; range(10**9) uses constant memory",
         "iterators pre-compute all values and store them internally", "iterators use more memory than lists for small sequences",
         "the memory benefit only applies to custom iterators, not built-in ones"),
        ("database connection pool warmup", "pre-establishes minimum connections at startup to avoid cold-start latency on first requests",
         "connections are always created on demand with no warmup benefit", "warmup means running queries to prime the query cache",
         "is only relevant for NoSQL databases"),
        ("avoiding unnecessary copies with memoryview", "provides zero-copy slicing of bytes/bytearray objects, critical for high-throughput binary protocols",
         "creates copies that are faster to access due to alignment", "only works with numpy arrays",
         "is slower than regular slicing for all practical purposes"),
        ("JIT compilation with PyPy vs CPython", "PyPy JIT compiles hot code paths to machine code at runtime, often 5-10x faster for long-running programs",
         "PyPy is always faster than CPython for all programs", "PyPy uses more memory with no speed benefit",
         "PyPy cannot run programs that use C extensions"),
    ]:
        base.append({
            "question_text": f"In performance optimization, what is correct about {concept}?\n\n  # Optimizing {{FN}}",
            "correct": f"It {correct}",
            "w1": f"It {w1}", "w2": f"It {w2}", "w3": f"It {w3}",
        })

    # Scenario questions  
    for q, c, w1, w2, w3 in [
        ("Your API endpoint takes 2 seconds to respond. cProfile shows 80%% time in a database query. What do you do?\n\n  # In {{FN}}",
         "Analyze the query with EXPLAIN, add appropriate indexes, consider caching frequent results in Redis",
         "Add more RAM to the database server", "Rewrite the query in raw SQL instead of ORM (which may not help if the plan is the same)",
         "Increase the connection pool size to 1000"),
        ("Your Python service uses 4GB RAM processing 1M records. How do you reduce it?\n\n  # Processing in {{FN}}",
         "Use generators/iterators for streaming processing, process in chunks, avoid loading all records into memory at once",
         "Use del statements after processing each record",
         "Switch to a language with better memory management",
         "Increase swap space to handle the memory usage"),
        ("A list comprehension processing 10M items is too slow. What alternatives should you consider?\n\n  # In {{FN}}",
         "Use numpy for vectorized operations, generator expression if memory is the issue, or multiprocessing.Pool for CPU-bound transformation",
         "Use a for loop instead since they are faster than comprehensions",
         "Switch to a dict comprehension which is inherently faster",
         "Use map() which is always faster than comprehensions"),
        ("Your async web server handles 100 concurrent requests but you need 10K. What bottleneck do you investigate?\n\n  # Scaling {{FN}}",
         "Check for blocking calls in async code, synchronous middleware, connection pool exhaustion, and file descriptor limits",
         "Add more CPU cores since asyncio is CPU-bound",
         "Switch to synchronous request handling which scales better",
         "Increase the number of worker threads to 10000"),
        ("How do you optimize repeated dictionary key lookups in a hot loop?\n\n  # In {{FN}} hot path",
         "Cache dict values in local variables before the loop; use local name binding for the dict itself",
         "Convert the dict to a list for faster iteration",
         "Use collections.OrderedDict which has faster lookups",
         "Switch to a database for key-value lookups"),
    ]:
        base.append({"question_text": q, "correct": c, "w1": w1, "w2": w2, "w3": w3})

    questions = []
    for i in range(count):
        b = base[i % len(base)].copy()
        fn = FUNCS[i % len(FUNCS)]
        questions.append({
            "question_text": b["question_text"].replace("{FN}", fn),
            "option_a": b["correct"].replace("{FN}", fn),
            "option_b": b["w1"].replace("{FN}", fn),
            "option_c": b["w2"].replace("{FN}", fn),
            "option_d": b["w3"].replace("{FN}", fn),
            "correct_answer": "A",
            "difficulty": "advanced",
            "topic": "performance_optimization",
        })
    return questions

print('gen_performance_optimization defined')


# ============= MAIN EXECUTION =============

def balance_answers(questions):
    """Enforce exactly 250 A, 250 B, 250 C, 250 D per 1000 questions."""
    assert len(questions) == 1000, f"Expected 1000 questions, got {len(questions)}"
    random.shuffle(questions)
    letters = ["A", "B", "C", "D"]
    keys = ["option_a", "option_b", "option_c", "option_d"]
    for i, q in enumerate(questions):
        target = letters[i // 250]
        cur = q["correct_answer"]
        if cur != target:
            ci = letters.index(cur)
            ti = letters.index(target)
            q[keys[ci]], q[keys[ti]] = q[keys[ti]], q[keys[ci]]
            q["correct_answer"] = target
    return questions


def write_question_bank(filepath, questions):
    """Write questions to a Python file."""
    with open(filepath, "w") as f:
        f.write('''"""\nQuestion Bank - 1000 questions\n"""\n\nQUESTIONS = [\n''')
        for q in questions:
            f.write("    {\n")
            for k in ["question_text", "option_a", "option_b", "option_c", "option_d",
                      "correct_answer", "difficulty", "topic"]:
                f.write(f'        "{k}": {repr(q[k])},\n')
            f.write("    },\n")
        f.write("]\n")


import os
random.seed(42)
APP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "app")

# File 8: concurrency_networking + security_auth
print("Generating question_bank_8.py...")
q8 = gen_concurrency_networking(500) + gen_security_auth(500)
q8 = balance_answers(q8)
write_question_bank(os.path.join(APP, "question_bank_8.py"), q8)
print(f"  Done: {len(q8)} questions")

# File 9: system_design + mixed_advanced
print("Generating question_bank_9.py...")
q9 = gen_system_design(500) + gen_mixed_advanced(500)
q9 = balance_answers(q9)
write_question_bank(os.path.join(APP, "question_bank_9.py"), q9)
print(f"  Done: {len(q9)} questions")

# File 10: devops_deployment + performance_optimization
print("Generating question_bank_10.py...")
q10 = gen_devops_deployment(500) + gen_performance_optimization(500)
q10 = balance_answers(q10)
write_question_bank(os.path.join(APP, "question_bank_10.py"), q10)
print(f"  Done: {len(q10)} questions")

# Aggregator file
print("Generating question_bank_all.py...")
agg_lines = [
    '\"\"\"',
    'Combined Question Bank - All 10 files aggregated (10000 questions total)',
    '\"\"\"',
    'from app.question_bank import QUESTION_BANK as _q1',
    'from app.question_bank_2 import QUESTIONS as _q2',
    'from app.question_bank_3 import QUESTIONS as _q3',
    'from app.question_bank_4 import QUESTIONS as _q4',
    'from app.question_bank_5 import QUESTIONS as _q5',
    'from app.question_bank_6 import QUESTIONS as _q6',
    'from app.question_bank_7 import QUESTIONS as _q7',
    'from app.question_bank_8 import QUESTIONS as _q8',
    'from app.question_bank_9 import QUESTIONS as _q9',
    'from app.question_bank_10 import QUESTIONS as _q10',
    '',
    'ALL_QUESTIONS = _q1 + _q2 + _q3 + _q4 + _q5 + _q6 + _q7 + _q8 + _q9 + _q10',
    '',
]
with open(os.path.join(APP, "question_bank_all.py"), "w") as f:
    f.write('\n'.join(agg_lines))

print("\nAll files generated successfully!")
